name: "Topic Tagger"
description: "This Topic Tagger is used to list the topic the user has used in his project"
branding:
  icon: 'at-sign'
  color: 'gray-dark'
inputs:
  start-point:
    description: "enter the starting point"
    required: true
    default: "./"
outputs:
  tags: # output will be available to future steps
    description: "list of topic used in this project"
runs:
  using: "node16"
  main: "dist/index.js"
