name: "Topic Tagger"
description: "This Topic Tagger is used to list the topic the user has used in his project"
branding:
  icon: "at-sign"
  color: "gray-dark"
inputs:
  start-point:
    description: "enter the starting point"
    required: true
    default: "./"
  version:
    description: "Enter the version you want to use. Options v1/v2/v3/v4"
    required: true
    default: "v4"
  github_token:
    description: 'GitHub token'
    required: true
outputs:
  tags: # output will be available to future steps
    description: "list of topic used in this project"
runs:
  using: "node16"
  main: "dist/index.js"
